### ISSUE TITLE
FS1 Login/Logout Page 

### ISSUE THREAD

**Issue by Karvel** [Shift3/boilerplate-client-angular#14]
## Desired Use Case

The library will provide a login and logout page.

### LP1

The login page form will include the following fields:

- Email
- Password

### LP2

Users will be able to reset their password from the login page.

### LP3

Users will be able to logout and view a page stating their session has ended.

## Actual/Current Behavior

The feature is not yet implemented.

## Steps to Implement This Feature

  1. Create a lazy loaded `AuthModule` and `AuthRoutingModule`.
  2. Create a `CoreModule` to store services.
  3. Create an `AuthService` with login and logout methods.
  4. Store and clear JWTs.
  5. Create a `SharedModule` for `ReactiveForm` imports.
  6. Create a `FormService` to facilitate interacting with Reactive Forms.
  7. Create a login component and login form.
  8. Create a logout component.

## Epic Checklist

- [x] [Add `AuthModule`](https://github.com/Shift3/boilerplate-client-angular/issues/16).
- [x] [Add `CoreModule`](https://github.com/Shift3/boilerplate-client-angular/issues/18).
- [x] [Add `AuthService`](https://github.com/Shift3/boilerplate-client-angular/issues/19).
- [x] [Handle JWTs](https://github.com/Shift3/boilerplate-client-angular/issues/20).
- [x] [Add `SharedModule`](https://github.com/Shift3/boilerplate-client-angular/issues/21).
- [x] [Add `FormService`](https://github.com/Shift3/boilerplate-client-angular/issues/22).
- [x] [Add Login](https://github.com/Shift3/boilerplate-client-angular/issues/23).
- [x] [Add Logout](https://github.com/Shift3/boilerplate-client-angular/issues/24).

## Pre-Testing TODOs

  1. Set up this project to run, either locally or through Docker, according to the readme.
  2. Test it against a working API. Right now, it is being built in tandem with https://github.com/Shift3/boilerplate-server-node. That project can also be be setup locally or through Docker.
  3. Update the `apiRoute` in the `environment.ts` file to point at the API (e.g. `http://localhost:3000`).
  4. Create a user through the API and keep the login credentials.

#### If you are not a member of this project, _skip this step_

_How do the users test this change?_

- [ ] Confirm that the webapp shows a loading screen.
- [ ] Confirm that the webapp loads the login screen when first loaded.
- [ ] Confirm that trying to login with incorrect credentials results in a 401.
- [ ] Confirm that logging in with the correct credentials is successful and shows a logout button.
- [ ] Confirm that clicking logout navigates to a logout component
- [ ] Confirm that returning to the login page after logging out shows the login form, and not the logout button.
