### ISSUE TITLE
FS2 Reset Password

### ISSUE THREAD

**Issue by Karvel** [Shift3/boilerplate-client-angular#15]
### RP1

The reset password form will contain a single field for users to input their email.

### RP2

The application will email a link with instructions on how to reset a password.

### RP3

The reset password link will redirect users to a form with the following fields:

- New Password
- Verify New Password

## Actual/Current Behavior

The feature is not yet implemented.

## Steps to Implement This Feature

  1. Add a `UserService`.
  2.Create a Forgot Password component with a form.
  3. Add a `forgotPassword` method to `UserService` (which causes the reset password email to be sent).
  4. Create the landing page component that the forgot password email redirects to with a form.
  5. Add the forgot password link to the login component template.
  6. Create a Reset Password component with a form.
  7. Add a `resetPassword` method to `UserService`.
  8. Implement reusable validators and apply to forms.

## Epic Checklist

- [x] [Add Reset Password](https://github.com/Shift3/boilerplate-client-angular/issues/38)
- [x] [Add Validation](https://github.com/Shift3/boilerplate-client-angular/issues/39)

## Pre-Testing TODOs

  1. Set up this project to run, either locally or through Docker, according to the readme.
  2. Test it against a working API. Right now, it is being built in tandem with https://github.com/Shift3/boilerplate-server-node. That project can also be be setup locally or through Docker.
  3. Update the `apiRoute` in the `environment.ts` file to point at the API (e.g. `http://localhost:3000`).
  4. Point this to an API that will send an email. https://github.com/Shift3/boilerplate-server-node can do this but requires SES credentials (get from the maintainers).
  5. Create a user through the API and keep the login credentials.

### Login

- [ ] Login now has form validation. Confirm that the form will not submit without a valid email and password.
 - [ ] Confirm that validation messages show and hide correctly as you enter values in the form.
- [ ] Click on the `Forgot Password?` link and confirm that it it navigates to the Forgot Password page.

### Forgot Password

- [ ] Confirm that the Forgot Password form has validation and will not submit without a valid email.
- [ ] Try entering the email you used to create an account. Confirm that you see a status message appear saying an email will be sent to that address.
- [ ] Check that email account and confirm that the email arrives.

### Reset Password

- [ ] Click on the link in the email and confirm that you return to the site to a Reset Password page.
- [ ] Enter a password and confirm it in the form.
- [ ] Make sure the form validation is working correctly. The password should require a minimum of 8 characters, and at least one digit and symbol. The confirm password field should have to match the password field.
- [ ] Reset the password and confirm that the webapp navigates back to the login screen.
- [ ] Try logging in with the old password and confirm it no longer works.
- [ ] Try logging in with the new password and confirm it works.

### Sign Up

- [ ] Confirm that form validation works on the sign up form. (Confirm Email and Confirm password will be added shortly in a styling pass).
