### ISSUE TITLE
Translation Epic TS3 - Connect selection to server-side update event for dynamic content

### ISSUE THREAD

**Issue by pratimasakinala** [Shift3/boilerplate-client-angular#230]
Note: The response from the server is currently in a shim on the client.

## Desired Use Case

Update the page's dynamic content to display text translation (when applicable) on language selection change.

## Steps to Implement This Feature

- [x] Send a request to the server to fetch the response including dynamic content from the database.
- [x] Update the models to add the `dynamicContent` property with the language code set as the index signature.
- [x] Update the models to add a client-side only `translatedContentForDisplay` to use in readonly situations (like the agent table).
- [x] Create helper methods in `AgentService` to unpack the dynamic content translation values in the response.
- [x] Update the stream in the `AgentListComponent` to combine the API response and active language streams, and pass those values to the helper methods.
- [x] Bind `translatedContentForDisplay` to the agent table.

## Pre-Testing TODOs

_What needs to be done before testing._

  1. Use the client-side shims or wait until the server returns the `dynamicContent` values in the agent list response.

#### If you are not a member of this project, _skip this step_

_How do the users test this change?_

  1. Log in as any user type.
  2. Open the agents view (Directory).
  3. Cycle through the different language options.
  4. Confirm that the description column in the table updates its translation correctly for each language.
