### ISSUE TITLE
Translation Epic TS1 - Enumerate the labels and field which should be addressed

### ISSUE THREAD

**Issue by pratimasakinala** [Shift3/boilerplate-client-angular#231]
## Desired Use Case
Below is the list of static content that needs to be addressed:
- Navigation:
  - [x] Logo img alt tag
  - [x] Navigation link labels
  - [x] Language Settings component:
    - [x] activeLanguage$
    - [x] language
  - [x] Login/Create Account button
- User Profile Actions:
  - [x] Update profile
  - [x] Change password
  - [x] Toggle Navigation bar
  - [x] Sign out
- Login page:
  - [x] Form link (Forgot password)
  - [x] Sign up card header and instruction
  - [x] Sign up button
  - [x] Forgot Password
- Directory page:
  - [x] Add Agent button
  - [x] Table headers
  - [x] Tooltip on Actions column
  - [x] Create/Edit form
- Users page:
  - [x] Add User button
  - [x] Table headers
  - [x] Tooltip on Actions column
  - [x] Create/Edit form
- Agencies page:
  - [x] Add Agency button
  - [x] Table header
  - [x] Tooltip on Actions column
  - [x] Create/Edit form
- Confirmation modal
  - [x] Modal title
  - [x] Modal Body text
  - [x] Modal buttons (Cancel, Log Out)
- Dynamic Form: 
  - [x] Form Title
  - [x] Form Fields
  - [x] Form buttons (Cancel, Create, Update)
  - [x] Form field validation error messages
  - [x] Form field placeholders
  - Form Select options (Currently the option values are read from the server. Need to revisit this when the dynamic content translation is added) (Separate issue created #267 )
  - Form title to show default language text in _italics_ when selected language is not the default language (Separate issue created #269 )
  - Form labels to show default language text in _italics_ when selected language is not the default language (Separate issue created #269 )
- [x] "No data" table content 
- [x] Image alt attributes
- [x] Toast messages
- [x] Revisit components to change `t` variable to `translate` in the templates.

## Steps to Implement This Feature

  1. For each of the above-mentioned pages, create language translation configuration for the labels, fields, etc.
  2. 
  3.
