### ISSUE TITLE
Translation Epic TS3 - Pages to be addressed for dynamic content translation

### ISSUE THREAD

**Issue by pratimasakinala** [Shift3/boilerplate-client-angular#234]
## Desired Use Case
- Directory Page:
  - [x] Table view 
  - [x] Form view
    - For fields:
      - [x] Description
- Additional pages to be listed after #233 is completed

## Steps to Implement This Feature

  1. Create a model for each data-table that requires dynamic content translation.
  2. The entity-language table should include the below properties:
     - [ ] entity_id (foreign key to entity table)
     - [ ] language_id (foreign key to language table)
     - [ ] entity_field/s that need translation
  3. Update UI to add "Add Translation" design.
  4. Add translations for available languages.
  5. Update the server's CRUD functionality to account for all translated content.
