### ISSUE TITLE
Translation Epic TS6 - Pages to be addressed for date, time and pluralization translation

### ISSUE THREAD

**Issue by pratimasakinala** [Shift3/boilerplate-client-angular#236]
## Desired Use Case

The webapp should also update localizations to match the selected language (date and time format, etc).

- Users Page:
  - Table view:
    - [x] Activated column
- Additional pages to be listed after #235 is completed.

## Actual/Current Behavior

This feature is not yet implemented.

## Steps to Implement This Feature

- [x] Add [`@ngneat/transloco-locale`](https://www.npmjs.com/package/@ngneat/transloco-locale?activeTab=readme) package to the project.
- [x] Wire up to `SharedModule` to expose to lazy loaded modules.
- [x]  Add `translocoDate` pipe to date field.

## Pre-Testing TODOs

_What needs to be done before testing._

  1. Make sure there is at least one user with an activated account..

#### If you are not a member of this project, _skip this step_

_How do the users test this change?_

  1. Log in as an admin.
  2. Click on Users.
  3. Look at the Activated Column of the users table.
  4. Cycle through the available languages
  5. Confirm that it updates to match each language's localization standards.

## Learning

<https://ngneat.github.io/transloco/docs/plugins/locale/>
<https://github.com/ngneat/transloco/issues/83>
