### ISSUE TITLE
Translation Epic TS3 - Store the user's preferred language in user model

### ISSUE THREAD

**Issue by pratimasakinala** [Shift3/boilerplate-client-angular#241]
## Desired Use Case

Store the user's preferred language setting in both user object and browser local storage. User object would be the primary source of truth and could be used to update the local value on page load. And then local can be the fallback for someone who is not logged in.

## Steps to Implement This Feature

- [x] Add user settings to state.
- [x] Create user settings CRUD methods.
- [x] Wire up user settings method to language settings component.
- [x] Consume the language settings from the returned user settings DTO.
- [x] Bootstrap the project to consume user settings values for language when possible.
- [x] Add unit tests.

## Pre-Testing TODOs

_What needs to be done before testing._

  1. Confirm the API is also on the translation epic branch.

#### If you are not a member of this project, _skip this step_

  1. Spin up the local server.
  2. Log in (as any user type).
  3. Change the selected language.
  4. Log out.
  5. Change to a different selected language while logged out.
  6. Log back in.
  7. Confirm that the client updates to the saved user settings language choice.
