### ISSUE TITLE
Translation Epic TS3 - Add UI in the dynamic-form for adding language translation

### ISSUE THREAD

**Issue by pratimasakinala** [Shift3/boilerplate-client-angular#246]
## Desired Use Case
Create UI For "Add Translation" design. Here is the clickable prototype of the design: https://www.figma.com/proto/zcHqO9Bpaz7SLu4kkoD6qD/Mel---Shift3-Boilerplate-copy?node-id=91%3A0&viewport=4238%2C-3130%2C0.49659252166748047&scaling=min-zoom

## Steps to Implement This Feature
  - [x] Create a new action item in the table view for `Add Translation` with the icon as shown in the prototype above. (Do we need to add any logic for when to show this beyond restricting it to editors and above)?
  - [x] Add the new action item only on the table (agent-table) that has content that will require translated text. (How do we want to determine this? For now, the client will set it explicitly since each table is unique. We might want to add some sort of flag to the list responses in the future though.)
  - [x] Open a pop-over when the `Add Translation` action is selected to provide a list of languages for which translation needs to be added. This list will not include the default language of the app as that is supported when updating a record. (We should probably have something in the UI to indicate languages with completed translations beyond the differences in button styles, like a checkmark). Maybe the API should determine what the default language is and filter it out from the results rather than the client?
  - [x] Upon a language selection on the pop-over list, open the "Update" form with only the fields that require translated text input enabled. All other fields to be disabled with pre-filled data. The form should have a new title ("Add Translation for Spanish"? "Add Agent Translation for Spanish"?)
  - [x] ~~In "Add Translation" form, display the form title, label, placeholder, error messages, buttons in the language for which translation is being added. The form title, form-label, form-error? to also be displayed in small text in the default language. It should display in whatever the chosen language is? That can be separate from the selected translation. (Maybe the person entering in Spanish data doesn't speak Spanish but they were given a list of translations to add).~~
  - [x] In edit/add translation mode, disable the language selection dropdown in the navigation. (Instead, the form name says "Set Translation for Spanish" to tell the user which language they selected. This title translates.)
  - [ ] Add a note on the forms that clearly mentioned the content (when in create/update view) will need to be in the default language even though the form title, labels, error messages & buttons are translated to the language selected from the top navigation dropdown.
