### ISSUE TITLE
Translation Epic TS1 - Need to add tests for the listed items

### ISSUE THREAD

**Issue by pratimasakinala** [Shift3/boilerplate-client-angular#256]
## Desired Use Case
Below is the list of tests that need to be added for locale and translation Epic:
- LanguageSettingsPresentationComponent
  - [ ] `getObjectProperty` method
- LanguageSettingsSmartComponent
  - [ ] `selectLanguage` method
- LanguageStateService
  - False case for:
    - [ ] Test with null or undefined to test failure of getActiveLanguage
    - [ ] Test with an empty array for failure of getAvailableLanguages
    - [ ] Test with a language that isn't listed in the LANGUAGE enum for failure of selectLanguage
    - [ ] Test if selectLanguage method calls translocoService correctly with the right values

## Actual/Current Behavior
These tests are not written.
