### ISSUE TITLE
Translation Epic TS3 - Dynamic Form Select options

### ISSUE THREAD

**Issue by pratimasakinala** [Shift3/boilerplate-client-angular#267]
## Desired Use Case

~~The Dynamic Form Select options need dynamic content translation support. The request from the client to include the `languageCode` in the header to run the query for. The server will read the languageCode from the header & return the list.~~

The client should translate local select option names (never values) when configured.

## Actual/Current Behavior

Currently, the option values are read from the server/database, or provided locally with no translation.

## Steps to Implement This Feature

- [x] Add a new `shouldOptionNameBeTranslatedByClient` boolean property to `ISelect`, set initialized value to false.
- [x] Translate option names in template when boolean is true.
- [x] Fix incorrect translation and update test description.
