### ISSUE TITLE
Translation Epic - Documentation for Locale & Translation

### ISSUE THREAD

**Issue by pratimasakinala** [Shift3/boilerplate-client-angular#273]
## Desired Use Case
- [ ] Reason for using Transloco over the built-in translation system:
  - Internationalization (i18n) requires a lot of configuration for set up. The dev environment can only be compiled with one language which doesn't help the developer as there is no real-time testing on language selection. The developer has to add the i18n attribute to all the template elements that require translation. Once the templates are setup, using the CLI to extract the code into messages file (in xlf format, which is difficult to read and maintain) includes all template elements with the i18n attribute. This file also includes the bootstrap labels, tags, etc for adding translation for various languages. This is helpful for ADA compliance. This process is not ideal for adding translation support as the application is being built as the templates will need to be extracted on new component creations. This means that the source message file content will have to be copied over to target (per language) message files without losing translations already added.
  - Whereas Transloco set up is really straightforward. The module provides a direct way to set up supported languages, default language and even a secondary fallback language. It uses JSON configuration files. There is no need to copy and paste content from the source file into the target file.
  - With all this said, the current phase will start with using Transloco and if we run into a case where it isn't working as expected, we will look into adding i18n.
- [ ] When & what to put in the translation files? If there's nothing to translate should these be in the translation file?
- [ ] How to use magic strings

## Steps to Implement This Feature

  1.
  2.
  3.
