### ISSUE TITLE
Translation Epic TS3 - Persist Language in Browser

### ISSUE THREAD

**Issue by Karvel** [Shift3/boilerplate-client-angular#274]
## Desired Use Case

The browser should persist the user's language choice.

## Actual/Current Behavior

The browser does not persist the language and it resets on reload.

## Steps to Implement This Feature

- [x] Add `transloco-persist-lang` dependency.
- [x] Simplify `TranslocoModule` importing to prevent duplicate imports.
- [x] Wire up `transloco-persist-lang` to `TranslocoRootModule`.

## Pre-Testing TODOs

_What needs to be done before testing._

  1. Run `yarn install` to install `transloco-persist-lang` dependency.

#### If you are not a member of this project, _skip this step_

_How do the users test this change?_

  1. Load the site.
  2. Select a non English language (excluding Tagalog for the moment).
  3. Confirm that the site switches to the chosen language.
  4. Reload the page.
  5. Confirm that it loads with the chosen language.
  6. Log in and try navigating throughout the site and reloading.
  7. Confirm that the chosen language still loads (we want to make sure it loads for the lazy loaded modules).

## Learning

<https://github.com/ngneat/transloco/blob/master/projects/ngneat/transloco-persist-lang/README.md>

References #241.
