### ISSUE TITLE
Translation Epic TS3 - Translate Page Title

### ISSUE THREAD

**Issue by Karvel** [Shift3/boilerplate-client-angular#279]
## Desired Use Case

The page titles should translate. Users should be able to see the route name in the browser title update to the selected language.

## Actual/Current Behavior

The page title changes based on route, but each route has a hard coded value.

## Steps to Implement This Feature

- [x] Create key value pairs for the webapp route titles in the language files.
- [x] Update the routes to reference the route keys.
- [x] Update `AppComponent` to consume keys from the route.
- [x] Add an inner stream to listen for language changes.
- [x] Call transloco and retrieve the translation for the latest language value.

#### If you are not a member of this project, _skip this step_

_How do the users test this change?_

  1. Open the site.
  2. Click on a routed link.
  3. Confirm that the browser title updates to show the new route name.
  4. Change the language and confirm that it updates to show the route name in that language.
  5. Navigate to another page and confirm that the route name updates in the browser title correctly.

## Learning

<https://ngneat.github.io/transloco/docs/language-api#langchanges>
<https://ngneat.github.io/transloco/docs/translation-api#selecttranslate>
