### ISSUE TITLE
Translation Epic TS1 - Refactor Dynamic-form title setup to be detached from routing `data`

### ISSUE THREAD

**Issue by pratimasakinala** [Shift3/boilerplate-client-angular#286]
## Desired Use Case
Separate the translation functionality for Dynamic form's title from router's `data.title` property.  This property is used mainly for setting the page's title. Since page title translation was added in #280 the previous change to this property ( title: {action, model}) was reverted to being a string. This change broke the current implementation of dynamic form's title translation support. In order to fix this bug, need to create a similar structure for the form's title value for each form as the page title translation is set up using `routing` key from the JSON files.

## Actual/Current Behavior
When Dynamic-form's title static content translation was previously implemented, it was coupled with the router's `data.title` property by converting it to an object with `action` and `model` keys.

## Steps to Implement This Feature
- [x] Create key-value pairs for the `dynamicForm.title` in the language files.
- [x] Update the smart components where the formConfigs are to reference the title keys.
- [x] Update the table components to be separate from the `dynamicForm` keys and to use `dynamicTable.tooltip` keys.

#### If you are not a member of this project, _skip this step_
  1. Open the site.
  2. Verify that the form title on the login page displays proper text.
  2. Upon login, create or edit an agency, agent & user.
  3. Confirm that the form title updates to show proper value.
  4. Change the language and confirm that it updates to show the form title in that language.
  5. Open user profile form, change password form and verify that the form titles show the proper title.
