### ISSUE TITLE
Translation Epic TS1 - Manage the magic strings used for translation for `dynamicForm`

### ISSUE THREAD

**Issue by pratimasakinala** [Shift3/boilerplate-client-angular#289]
## Desired Use Case
Manage the magic strings like `dynamicForm.action` in an Interface.

## Actual/Current Behavior
There are a lot of hard-coded strings in the templates that are needed by transloco to perform translation on the property defined by these strings.

## Steps to Implement This Feature
  - [x] Create an interface for `dynamicForm` key from the JSON files.
  - [x] Create an interface for the following first level of nested keys under `dynamicForm` in the language JSON files:
     - [x] action
     - [x] error
     - [x] label
     - [x] placeholder
     - [x] title
  - [x] Update components to use the new `DynamicForm` class when initializing a new form.

#### If you are not a member of this project, _skip this step_

  1. Open the site.
  2. On any of the list views, create/update a record and verify that the form title, labels, placeholders, error messages & buttons content are displayed properly.
  3. Change the language selection & verify that the above step is still valid.
