### ISSUE TITLE
Translation Epic TS1 - Manage the magic strings used for translation for `dynamicTable`

### ISSUE THREAD

**Issue by pratimasakinala** [Shift3/boilerplate-client-angular#290]
## Desired Use Case
Manage the magic strings like `dynamicTable.header` in an Interface.

## Actual/Current Behavior
There are a lot of hard-coded strings in the templates that are needed by transloco to perform translation on the property defined by these strings.

## Steps to Implement This Feature
  - [x] Move `resendActivationEmail` from `dynamicTable.body` to `dynamicTable.tooltip`.
  - [x] Create an interface for `dynamicTable` key from the JSON files.
  - [x] Create an interface for the following first level of nested keys under `dynamicTable` in the language JSON files:
    - [x] header
    - [x] body
    - [x] tooltip

#### If you are not a member of this project, _skip this step_

  1. Open the site.
  2. On any of the list views, verify that the table headers, body, tooltips & add-button content are displayed properly.
  3. Change the language selection & verify that the above step is still valid.
