### ISSUE TITLE
Translation Epic TS3 - Add Select Language UI for Translation CRUD

### ISSUE THREAD

**Issue by Karvel** [Shift3/boilerplate-client-angular#303]
## Desired Use Case

The user (editors and above) should be able to select an existing record which has dynamic translation enabled and choose the language to add the translations for that record. It should indicate which languages have already have translated values for the given record. Upon selecting a language, clicking on the language button should take the user to a form where they can add the translations for the selected language (will be implemented separately).

The language select UI should be in a popover to improve accessibility (when compared to a modal).

Create UI For "Add Translation" design. Here is the clickable prototype of the design: https://www.figma.com/proto/zcHqO9Bpaz7SLu4kkoD6qD/Mel---Shift3-Boilerplate-copy?node-id=91%3A0&viewport=4238%2C-3130%2C0.49659252166748047&scaling=min-zoom

## Actual/Current Behavior

The feature is not yet implemented.

## Steps to Implement This Feature

- [x] Create `SelectLanguageComponent` to work as a reusable popover.
- [x] Add translation values for the popover instructions and action button in the table.
- [x] Wire up popover template to table component.
- [x] Add button to table to open popover.
- [x] Emit select language event to parent components.
- [x] Call popover and tooltip programmatically on same button to prevent collisions.

## Pre-Testing TODOs

_What needs to be done before testing._

  1. The API functionality needs to be merged in (or you need to add shims to test without an updated API).

#### If you are not a member of this project, _skip this step_

_How do the users test this change?_

  1. Log in as an editor or above.
  2. Go to the agent list.
  3. Confirm that there is a new translate button in the table in the Actions column.
  4. Confirm that it has a tooltip on hover.
  5. Confirm that clicking or tapping on the button opens a tooltip.
  6. Confirm that the popover has the names of the languages as buttons in a list.
  7. Confirm that the popover shows a checkbox next to languages with completed translations.
  8. Confirm that the on hover tooltip does not show when it shouldn't (e.g. when you stop hovering over the button).

## Learning

<https://ng-bootstrap.github.io/#/components/popover/api>
<https://ng-bootstrap.github.io/#/components/tooltip/api>

References #222.
References #246.
