### ISSUE TITLE
Translation Epic TS3 - Add Dynamic Translation to Agent Detail Form

### ISSUE THREAD

**Issue by Karvel** [Shift3/boilerplate-client-angular#310]
## Desired Use Case

The webapp should be able to load a form where a user can set translations for records with dynamic content. This form should disable the non-dynamic fields. It should load the selected language values when available. It should state the selected language in the form title to improve the UX.

## Actual/Current Behavior

This feature is not yet implemented.

## Steps to Implement This Feature

- [x] Trigger call to `set-translate` route using event emitters instead of state.
- [x] Add form title translations for "Set Translation".
- [x] Update `AgentDetailComponent` to handle the `set-translation` route:
  - [x] Add a `isSetTranslation` boolean.
  - [x] Use `isSetTranslation` to disable form controls.
  - [x] Use `isSetTranslation` to update form title and submit method.
- [x] Update the dynamic form title to consume translation parameters, if available.
- [x] Wire up the `set-translation/:id/:languageCode` route.
- [x] Initialize `CreateAgentResolver` with default language dynamic content.

## Pre-Testing TODOs

_What needs to be done before testing._

  1. Change DB values in x collection to y.

#### If you are not a member of this project, _skip this step_

_How do the users test this change?_

  1. Navigate to x screen
  2. Click on y button
  3. Observe z result

References #270.
