### ISSUE TITLE
Translation Epic TS1 - Rename `es-ES` language code to `es-MX`

### ISSUE THREAD

**Issue by pratimasakinala** [Shift3/boilerplate-client-angular#314]
## Desired Use Case
`es-ES` is continental Spanish from Spain, which most Spanish speakers in the US don't speak. The two are mostly interchangeable, but the difference is greater than the difference between American and British English, as a comparison. `es-MX` makes perfect sense because it's the most used variation in the US.

## Actual/Current Behavior
Currently, the application is initialized with `es-ES`.

## Steps to Implement This Feature
- [x] Rename the JSON file
- [x] Update the import into the index file
- [x] Rename `es-ES` to `es-MX` in the `LANGUAGE` enum
- [x] Update language-state-service test file to rename the language code

## Learning
https://en.wikipedia.org/wiki/Spanish_language_in_the_United_States#Varieties
