### ISSUE TITLE
Translation Epic TS3 - Update the agent form request payload to include `dynamicContent` property 

### ISSUE THREAD

**Issue by pratimasakinala** [Shift3/boilerplate-client-angular#318]
## Desired Use Case
Update the request payload to include `dynamicContent` key as below:
```
body: {
  "fullName": "",
  ...
  "dynamicContent": {
    "en-US": {
      "description": ""
    }
  }
}
```
The above example is valid for POST/PUT for `agent` route. The same structure will apply to POST/PUT for `agent/translation` route with the only change being the language code will be that of the language for which translation is being set.

## Actual/Current Behavior
The current payload doesn't include `dynamicContent` or `description` properties.

## Steps to Implement This Feature
- [x] Update the `IAgentRequest` interface & its associated class to include `dynamicContent` property.
- [x] Create a local variable `dynamicContentDTO` which is a new instance of `AgentTranslation`.
- [x] Create a payload for `dynamicContentPayload` using `dynamicContentDTO` as the requestPayload.
- [x] Update `buildRequestPayload` method in form.service to set the value of `nestedProperty` property on the requestPayload.
- [x] Create requests to create/update agent translations.
