### ISSUE TITLE
Translation Epic TS3 - Prevent Accidental Reassignment in Request Payloads

### ISSUE THREAD

**Issue by Karvel** [Shift3/boilerplate-client-angular#329]
## Desired Use Case

Unpacking nested payloads should not be a side effect for `buildRequestPayload()`. It should be separated into its own method for clarity.

## Actual/Current Behavior

The current method can accidentally overwrite objects with nested values:

```ts
{
    id: 1,
    name: 'Test Tester',
    ...
    role: {
        id: 1,
        roleName: 'Admin'
    },
    agency: {
        id: 1,
        agencyName: 'TestCo'
    }
}
```

becomes

```ts
{
    id: 1,
    name: 'Test Tester',
    ...
    role: 1,
    agency: 'TestCo'
}
```
## Steps to Implement This Feature

  - [x] Create new `buildNestedRequestPayload()`.
  - [x] Move nested property logic.
  - [x] Add tests.
  - [x] Use `buildNestedRequestPayload()` when unpacking `dynamicContent`.
  - [x] Use `buildNestedRequestPayload()` when mapping from nested property to parent object (e.g. getting form values for role and agency from select fields).
  - [x] Fix breaking test in `LanguageStateService`.

## Pre-Testing TODOs

_What needs to be done before testing._

  1. Serve from the translation epic branch on the API.

#### If you are not a member of this project, _skip this step_

_How do the users test this change?_

  1. Login as an admin.
  2. Create a new user (this requires setting role and agency).
  3. Confirm that the values set correctly.
  4. Add a translation for an agent description value.
  5. Confirm that the values set correctly.
