### ISSUE TITLE
FS4 Navigation

### ISSUE THREAD

**Issue by Karvel** [Shift3/boilerplate-client-angular#53]
### NB1

The reusable navigation bar will include the following items:

- Dashboard (Home)
- Manage Users (Admin)
- List View
- Profile Picture (links to user account settings)
- Login/Logout    

### NB2

The navigation bar module will allow developers to toggle between two types:

- Top Navigation Bar
- Side Navigation Bar

## Actual/Current Behavior

The feature is not yet implemented.

## Steps to Implement This Feature

1. Create a `ContentModule` - this the the dashboard from [FS5](https://github.com/Shift3/boilerplate-client-angular/projects/7) but we need the scaffolding now.
2. Create a `TopNavigationComponent`.
3. Create a `SideNavigationComoonent`.
4. Consider nice to haves:
     - Creating a facade for toggling navigation type via `ComponentFactoryResolver`.
     - Creating `NavigationBaseComponent` to store methods and list of iterable links.

## Epic Checklist

- [x] [Create `ContentModule`](https://github.com/Shift3/boilerplate-client-angular/issues/56)
- [x] [Create `TopNavigationComponent`](https://github.com/Shift3/boilerplate-client-angular/issues/57)
- [x] [Create `SideNavigationComponent`](https://github.com/Shift3/boilerplate-client-angular/issues/58)
- [x] [Use Correct Signup Endpoint](https://github.com/Shift3/boilerplate-client-angular/issues/70)
- [x] [Clicking Logo Does Not Return to Login](https://github.com/Shift3/boilerplate-client-angular/issues/77)

## Pre-Testing TODOs

  1. Set up this project to run, either locally or through Docker, according to the readme.
  2. Test it against a working API. Right now, it is being built in tandem with https://github.com/Shift3/boilerplate-server-node. That project can also be be setup locally or through Docker.
  3. Update the `apiRoute` in the `environment.ts` file to point at the API (e.g. `http://localhost:3000`).
  4. Point this to an API that will send an email. https://github.com/Shift3/boilerplate-server-node can do this but requires SES credentials (get from the maintainers).
  5. Create a user through the API and keep the login credentials.
  6. Run `yarn install` to get the new dependencies (ng-bootstrap).

### Login

- [ ] Log in with a valid account and confirm that navigates to the dashboard.

### Dashboard (Content)

The Dashboard has navigation elements. This project can support either a horizontal top navigation bar, or a vertical side navigation bar. So you can test both, I have placed some demo buttons that toggle between the different kinds of navigation bars. This is going to be removed when I merge this upstream, it's just so you can test both bars. (The idea is that this site wouldn't show both bars as is at the same time, so ignore if they look weird when both on screen at the same time).

- [ ] Confirm that the layout works. The top navigation bar should be at the top of the screen and extend all the way across.
- [ ] Confirm that the side bar is on the left side of the screen and extends all the way vertically (it won't overlap with the top bar when both are visible). The menu links should be vertically centered.
- [ ] Confirm that the content is centered on the screen (up until 1980pixels wide).
- [ ] Confirm that the dropdown menu on the top navigation bar for "Hi Username" has "Name" to the left, centered, and three menu items to the right ("Username" and "Name" are placeholder values).
- [ ] Confirm that the dropdown menu on the top navigation bar for "Hi Username" has "Name" to the left, centered, and three menu items to the right ("Username" and "Name" are placeholder values).
- [ ] Confirm that each link in the top navigation works. Some of the links go to pages that don't exist yet and result in a 404:
    - Logo - `/` - Should go back to Login
    - Directory - `/content` - You are already here
    - Users - `admin/user-list` - 404
    - Settings - `admin/settings` - 404
    - Profile - `/user/profile` - 404
    - Change Password - `/user/change-password` - 404
    - Sign Out - `/auth/logout` - Will show a confirmation modal first
- [ ] Confirm that each link in the side navigation works. Some of the links go to pages that don't exist yet and result in a 404:
    - Logo - `/` - Should go back to Login
    - Directory - `/content` - You are already here
    - Users - `admin/user-list` - 404
    - Settings - `admin/settings` - 404
    - Profile - `/user/profile` - 404
    - Change Password - `/user/change-password` - 404
    - Sign Out - `/auth/logout` - Will show a confirmation modal first
- [ ] Test the Sign Out button in the top navigation bar. It should show a confirmation modal when you click on it.
- [ ] Confirm that the modal does nothing when you click "Cancel" or outside of the modal window to close it.
- [ ] Confirm that the modal takes you to the log out screen if you click "Sign Out".
- [ ] Test the Sign Out button in the side navigation bar. It should show a confirmation modal when you click on it.
- [ ] Confirm that the modal does nothing when you click "Cancel" or outside of the modal window to close it.
- [ ] Confirm that the modal takes you to the log out screen if you click "Sign Out".
- [ ] Test the keyboard functionality of the top navigation bar. Confirm that you can navigate through every menu item and interact with them.
- [ ] Test the keyboard functionality of the side navigation bar. Confirm that you can navigate through every menu item and interact with them.
- [ ] Test the responsiveness of the top navigation. It should switch to a hamburger menu on smaller screens.
- [ ] Test the responsiveness of the side navigation. It should switch to a vertical navigation bar on smaller screens (this will change when we get a design for the side navigation version of the webapp).

## Learning

_Describe the research stage._

_Links to blog posts, patterns, libraries or addons that could be used to solve this problem._
