### ISSUE TITLE
FS6 List View 

### ISSUE THREAD

**Issue by Karvel** [Shift3/boilerplate-client-angular#55]
This epic has been redesigned since the below scope was written out. I am going to still use this issue since the sub branches had already been part of an `epic-fs6` branch.

## LV1

The list view will be a generic component that can render a list of user-created records for any data entity within the application.

### LV2

By default, the list view items will contain the following:

- Thumbnail (ex: Profile Pic, Item Pic, Logo)
- Name
- Description
- Contact Information
    - Address
        - Address 1, Address 2, City, State, Zip Code
    - Phone
    - Email
- Multi-Document Upload 
    - With “optionized” labels similar to Categories (See below)
- Categories (Admin-created in AP1)
    - “Optionized” to work 1 of 2 ways:
        - Multi-Select
        - Single-Select

### LV3

The list view will allow users to search and filter the items. (FS7)

### LV4

The list view will allow users to specify the number of records per page that should be displayed. This selection will persist until the user changes it.

### LV5

The list view will be toggle-able with a Map view that displays pins to indicate the same data elements as the list view.

## Actual/Current Behavior

The feature is not yet implemented.

## Steps to Implement This Feature

  1. Add the `agent-list` view.
  2. Add `AgentService` and API methods.
  3. Add the `agent-detail` with `create-agent` and `update-agent` routes.
  4. Prefetch the data via resolvers.
  5. Guard the routes and the options on `agent-list` based on role.
  6. Write tests for the service, state service, guards, and resolvers.

## Epic Checklist

- [x] [Add Agent List View](https://github.com/Shift3/boilerplate-client-angular/issues/102)
- [x] [Add Role Guards to Agent List](https://github.com/Shift3/boilerplate-client-angular/issues/118)
- [x] [Finish Agent CRUD](https://github.com/Shift3/boilerplate-client-angular/issues/120)

## Pre-Testing TODOs

_What needs to be done before testing._

  1. Change DB values in x collection to y.

#### If you are not a member of this project, _skip this step_

_How do the users test this change?_

  1. Navigate to x screen
  2. Click on y button
  3. Observe z result
