### ISSUE TITLE
FS3 User Accounts

### ISSUE THREAD

**Issue by Karvel** [Shift3/boilerplate-client-angular#73]
### UA1

When creating a new user account, the following fields will be required:

- Email
- Confirm Email
- Password (Create Invitation Email with Token)
- Profile Picture (Photo Upload)
- First Name
- Last Name

Once an account has been created, users will receive a welcome email. ([FS6](https://github.com/Shift3/boilerplate-client-angular/projects/8))

**_Note:_** *The invitation email will contain a link back to the application where the user can create a password by completing the following form:

- Auto-Generated Password
- New Password (with Strength Meter)
- Confirm New Password*

### UA2

(Optional): After confirming the new account, Users will be prompted to select Categories in their profile:

- Categories (Admin-created in [FS6](https://github.com/Shift3/boilerplate-client-angular/projects/8))
    - “Optionized” to work 1 of 2 ways:
        - Multi-Select
        - Single-Select
    - **_Note:_** *Determined at dev-time when spinning up the boilerplate, based on the client scope.*

## Actual/Current Behavior

This feature is not yet implemented.

## Steps to Implement This Feature

  1. Add an `AdminModule` with routed components.
  2. Add an `UserModule` with routed components.
  3. Improve app-wide styling.
  4. Wire up role awareness and role checks.
  5. Add full User CRUD.
  6. Look up role list from API.

## Epic Checklist

- [x] [Add Admin Module](https://github.com/Shift3/boilerplate-client-angular/issues/89)
- [x] [Add User Module](https://github.com/Shift3/boilerplate-client-angular/issues/91)
- [x] [Improve Form and Layout Styling](https://github.com/Shift3/boilerplate-client-angular/issues/93)
- [x] [Implement User Roles](https://github.com/Shift3/boilerplate-client-angular/issues/96)
- [x] [Implement Role Checks](https://github.com/Shift3/boilerplate-client-angular/issues/98)
- [x] [Implement User Update and Delete](https://github.com/Shift3/boilerplate-client-angular/issues/100)
- [x] [Add Role Lookup](https://github.com/Shift3/boilerplate-client-angular/issues/113)

## Pre-Testing TODOs

_What needs to be done before testing._

  1. Change DB values in x collection to y.

#### If you are not a member of this project, _skip this step_

_How do the users test this change?_

  1. Navigate to x screen
  2. Click on y button
  3. Observe z result
